[build]
  base = "react-three"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../netlify.toml"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_CONFIG_OPTIONAL = "false"
